name: Send Deployment Event to GA4

on:
  push:
    branches: [main]

jobs:
  send-ga4-event:
    runs-on: ubuntu-latest
    steps:
      - name: Send GA4 Event
        uses: Dylan700/ga4-action@v1.4.1
        with:
          event-name: deployment
          measurement-id: ${{ secrets.GA4_MEASUREMENT_ID }}
          api-secret: ${{ secrets.GA4_API_SECRET }}
          client-id: ${{ github.run_id }}
          params: '{"branch":"${{ github.ref_name }}","commit":"${{ github.sha }}","repo":"${{ github.repository }}"}'
