name: Lighthouse Performance Audit

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Lighthouse CI
        run: npm i -g @lhci/cli@0.12.x

      - name: Run Lighthouse CI against production URL
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -z "${{ secrets.SITE_URL }}" ]; then echo "SITE_URL secret not set"; exit 1; fi
          lhci autorun --collect.url=${{ secrets.SITE_URL }} --upload.target=temporary-public-storage

      - name: Save Lighthouse report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: .lighthouseci/*
